// ============================================================
// TripForge - Comprehensive Type Definitions
// ============================================================
//
// This file is the single source of truth for all TypeScript
// interfaces and enums used across the TripForge application.
// Any new data structures should be added here to maintain
// type safety throughout the frontend and backend.
// ============================================================

// ────────────────────────────────────────────────────────────
// Enums
// ────────────────────────────────────────────────────────────

/**
 * Identifies which AI provider is being used for a given operation.
 */
export enum AIProvider {
  Gemini = 'gemini',
  HuggingFace = 'huggingface',
}

// ────────────────────────────────────────────────────────────
// Core Data Models (New)
// ────────────────────────────────────────────────────────────

/**
 * A single activity within a time block.
 * Represents one thing the traveler will do (visit a museum,
 * eat at a restaurant, take a bus, etc.).
 */
export interface Activity {
  /** Display name of the activity */
  name: string;
  /** Short description generated by the primary AI */
  description: string;
  /** Richer description optionally enhanced by HuggingFace */
  enhancedDescription?: string;
  /** Human-readable duration (e.g. "2 hours") */
  duration: string;
  /** Estimated cost in the local currency */
  cost: number;
  /** Practical tips for the traveler */
  tips?: string;
  /** Whether advance booking is needed */
  bookingRequired: boolean;
  /** Direct URL to book, if applicable */
  bookingUrl?: string;
  /** Flag for activities that are especially photogenic */
  photoWorthy?: boolean;
  /** Physical address or location name */
  address?: string;
  /** High-level category for icon/color coding in the UI */
  category?: 'Food' | 'Attraction' | 'Transport' | 'Entertainment';
}

/**
 * A chunk of a day grouped by period (Morning, Lunch, etc.).
 */
export interface TimeBlock {
  /** Which part of the day this block covers */
  period: 'Morning' | 'Lunch' | 'Afternoon' | 'Dinner' | 'Evening';
  /** Human-readable time range (e.g. "9:00 AM – 12:00 PM") */
  timeRange: string;
  /** Ordered list of activities within this block */
  activities: Activity[];
}

/**
 * A single day inside an itinerary (new structured format).
 */
export interface Day {
  /** 1-indexed day number */
  dayNumber: number;
  /** Optional ISO date string for the specific calendar day */
  date?: string;
  /** Thematic label (e.g. "Cultural Exploration") */
  theme: string;
  /** Ordered time blocks that make up this day */
  timeBlocks: TimeBlock[];
  /** Sum of all activity costs for the day */
  dayTotal: number;
  /** Transport / logistics notes */
  logistics?: string;
  /** Weather summary, optionally enriched by HuggingFace */
  weatherForecast?: string;
}

// ────────────────────────────────────────────────────────────
// Legacy Data Models (Backward Compatibility)
// ────────────────────────────────────────────────────────────
// These interfaces mirror the original shapes used by the
// existing UI components and API route handlers.  They are
// exported so that current code keeps working without changes.
// ────────────────────────────────────────────────────────────

/**
 * Legacy activity shape used by ItineraryView and the
 * generate-itinerary route handler.
 */
export interface LegacyActivity {
  id: string;
  time: string;
  title: string;
  description: string;
  location: string;
  duration: string;
  cost: string;
  category:
    | 'sightseeing'
    | 'food'
    | 'adventure'
    | 'culture'
    | 'relaxation'
    | 'transport'
    | 'shopping';
  tips?: string;
}

/**
 * Legacy day plan used by ItineraryView and the
 * generate-itinerary route handler.
 */
export interface DayPlan {
  day: number;
  date: string;
  theme: string;
  activities: LegacyActivity[];
}

// ────────────────────────────────────────────────────────────
// Itinerary (Unified — new fields + legacy fields)
// ────────────────────────────────────────────────────────────

/**
 * The top-level itinerary returned by the AI pipeline.
 *
 * `days` is typed as `DayPlan[]` to match every existing
 * component and API route handler.  For new code that uses
 * the structured `Day` / `TimeBlock` format, see `AIItinerary`.
 */
export interface Itinerary {
  // ── Shared ──────────────────────────────────────────────
  /** Unique identifier (UUID v4) */
  id: string;
  /** Primary destination */
  destination: string;
  /** Optional ISO start date */
  startDate?: string;
  /** ISO timestamp of creation */
  createdAt: string;

  // ── New fields ──────────────────────────────────────────
  /** User-facing trip name (new) */
  name?: string;
  /** Trip length in days (new) */
  duration?: number;
  /** Travel style label (new) */
  travelStyle?: string;
  /** Budget tier label (new) */
  budgetLevel?: string;
  /** Grand total estimated cost (new, numeric) */
  totalEstimatedCost?: number | string;
  /** AI-generated packing suggestions (new) */
  packingTips?: string[];
  /** AI-generated general travel tips (new) */
  generalTips?: string[];
  /** ISO timestamp of last modification (new) */
  updatedAt?: string;

  // ── Legacy fields ───────────────────────────────────────
  /** Short title generated by the AI */
  title?: string;
  /** AI-generated summary paragraph */
  summary?: string;
  /** Optional ISO end date */
  endDate?: string;
  /** Number of calendar days (legacy) */
  totalDays?: number;
  /** Budget tier string ("budget" | "moderate" | "luxury") */
  budget?: string;
  /** Currency code (e.g. "USD") */
  currency?: string;
  /** Day-by-day breakdown — legacy flat format */
  days: DayPlan[];
  /** Flat packing list (legacy) */
  packingList?: string[];
  /** Flat travel tips list (legacy) */
  travelTips?: string[];
  /** Estimated total cost as display string (legacy) */
  estimatedTotalCost?: string;
}

/**
 * New structured itinerary using `Day` / `TimeBlock` / `Activity`.
 * Use this when building new features; migrate existing components
 * to this shape over time.
 */
export interface AIItinerary {
  id: string;
  name: string;
  destination: string;
  duration: number;
  startDate?: string;
  travelStyle: string;
  budgetLevel: string;
  days: Day[];
  totalEstimatedCost: number;
  packingTips?: string[];
  generalTips?: string[];
  createdAt: string;
  updatedAt: string;
}

// ────────────────────────────────────────────────────────────
// User Input
// ────────────────────────────────────────────────────────────

/**
 * The shape of data collected from the trip form before
 * being sent to the AI generation endpoint.
 */
export interface UserInput {
  /** Where the user wants to go */
  destination: string;
  /** How many days (defaults to AI suggestion if omitted) */
  duration?: number;
  /** Tags like "history", "food", "nightlife" */
  interests: string[];
  /** Free-text or structured budget preference */
  budget?: string;
  /** E.g. "Adventure", "Luxury", "Budget" */
  travelStyle?: string;
  /** Accessibility or dietary constraints */
  constraints?: string[];
  /** Optional ISO start date */
  startDate?: string;
  /** Number of travelers */
  groupSize?: number;
}

// ────────────────────────────────────────────────────────────
// Legacy Preferences (used by TripForm, prompts, storage)
// ────────────────────────────────────────────────────────────

/**
 * Preferences shape consumed by the trip form, the prompt
 * builder, and the local-storage persistence layer.
 */
export interface TripPreferences {
  destination: string;
  startDate: string;
  endDate: string;
  budget: 'budget' | 'moderate' | 'luxury';
  interests: string[];
  travelStyle: 'relaxed' | 'balanced' | 'packed';
  travelers: number;
  specialRequirements?: string;
}

// ────────────────────────────────────────────────────────────
// API Request / Response Contracts
// ────────────────────────────────────────────────────────────

/**
 * Body sent to POST /api/generate-itinerary
 */
export interface GenerateItineraryRequest {
  preferences: TripPreferences;
}

/**
 * Response from POST /api/generate-itinerary
 */
export interface GenerateItineraryResponse {
  success: boolean;
  itinerary?: Itinerary;
  error?: string;
}

/**
 * Body sent to POST /api/enhance-content
 */
export interface EnhanceContentRequest {
  content: string;
  type: 'description' | 'tips' | 'summary';
}

/**
 * Response from POST /api/enhance-content
 */
export interface EnhanceContentResponse {
  success: boolean;
  enhanced?: string;
  error?: string;
}

// ────────────────────────────────────────────────────────────
// Local Persistence
// ────────────────────────────────────────────────────────────

/**
 * Shape of a trip saved to localStorage.
 */
export interface SavedTrip {
  id: string;
  itinerary: Itinerary;
  preferences: TripPreferences;
  savedAt: string;
}
